routes/web.php
<?php

use RealRashid\SweetAlert\Facades\Alert;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('/', function () {
    Alert::success('Success Title', 'Success Message');
    return view('welcome');
});
Route::get('/test', function () {
    return view('test');
});

Route::get('access-denied', function () {
    return view('errors.403');
});

Route::get('/about', function () {
    return view('about');
});

Route::get('/contact', 'ContactController@index')->name('contact.index');
Route::post('/contact', 'ContactController@store')->name('contact.store');

Route::resource('cars', 'CarController');
Route::post('import', 'CarController@import')->name('car.import');
Route::get('export', 'CarController@export')->name('car.export');
Route::get('/', 'CarController@getCars')->name('cars.getCars');
Route::patch('cars/{car}', 'CarController@updateLikes')->name('cars.updateLikes');
Route::resource('brands', 'BrandController');
Route::resource('categories', 'CategoryController');
Route::resource('bookings', 'BookingController')->middleware(['auth', 'verified']);

Auth::routes(['verify' => true]);

Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

Route::group(['prefix' => 'dashboard', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@index')->name('dashboard.index');
    Route::get('/cars', 'AdminController@getCars')->name('dashboard.cars');
    Route::get('/bookings', 'AdminController@getBookings')->name('dashboard.bookings');
    Route::get('/payments', 'AdminController@payments')->name('dashboard.payments');
    Route::get('/bookings/toggle-status/{id}', 'AdminController@toggle_status')->name('bookings.status');
    Route::get('/reports', 'AdminController@reports')->name('dashboard.reports');
});

// Route::group(['prefix' => 'dashboard', 'middleware' => ['role:admin']], function() {
//     Route::get('/', 'AdminController@welcome');
//     Route::get('/manage', ['middleware' => ['permission:manage-admins'], 'uses' => 'AdminController@manageAdmins']);
// });

//**************Profiles Routes ****************************
Route::prefix('/profile')->middleware('auth')->group(function(){
    Route::get('/passwordChange','ProfileController@changePassword');
    Route::post('/passwordChange/{id}','ProfileController@postChangePassword');
    Route::get('/editProfile/{id}','ProfileController@editprofile');
    Route::post('/editprofile/{id}','ProfileController@posteditprofile');
});

resources/views/partials/book.blade.php
<form method="POST" action="{{ route('bookings.store') }}">
    @csrf
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="pickup_loc">Pickup Location</label>
        <input type="text" class="form-control" id="pickup_loc" name="pickup_loc">
      </div>
      <div class="form-group col-md-6">
        <label for="drop_loc">Drop Location</label>
        <input type="text" class="form-control" name="drop_loc" id="drop_loc">
      </div>
    </div>
    <div class="form-group">
      <label for="pickup_time">Pickup Time</label>
      <input type="time" class="form-control" id="pickup_time" name="pickup_time" placeholder="1234 Main St">
    </div>
    <div class="form-group">
      <label for="drop_time">Drop Time</label>
      <input type="time" class="form-control" id="drop_time" name="drop_time" placeholder="Apartment, studio, or floor">
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="pickup_date">Pickup Date</label>
        <input type="date" class="form-control" id="pickup_date" max="3000-12-31" 
        min="1000-01-01" name="pickup_date">
      </div>
      <div class="form-group col-md-4">
        <label for="drop_date">Drop Date</label>
        <input type="date" class="form-control" id="drop_date" max="3000-12-31" 
        min="1000-01-01" name="drop_date">
      </div>
    </div>
    <input type="hidden" name="car_id" value="{{$car->id}}">
    <button type="submit" class="btn btn-primary">Book</button>
</form>

resources/views/partials/car-edit.blade.php
<div class="modal fade" id="editModal{{ $car->id }}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="editModalLabel">Edit Car</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
            <form action="{{route('cars.show', ['car' => $car->id])}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="name">Name</label>
                        <input type="name" class="form-control" id="name" name="name" value="{{$car->name}}">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="price">Price</label>
                        <input type="number" class="form-control" id="price" name="price" value="{{$car->price}}">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="passengers">Passengers</label>
                        <input type="number" class="form-control" id="passengers" name="nop" value="{{$car->nop}}">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="status"><strong>Status</strong> <em>[Available=1, Not-Available=0]</em> </label>
                        <select id="status" name="status" class="form-control">
                            <option value="{{$car->status}}">{{$car->status}}</option>
                            <option value="1">1</option>
                            <option value="0">0</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                  <label for="description">Description</label>
                  <textarea name="description" id="description" class="form-control" cols="30" rows="4">{{$car->description}}</textarea>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                    <img src="{{asset($car->image)}}" style="width:100px; height:100px" alt="car-image">
                    </div>
                    <div class="form-group col-md-8">
                        <label for="image">Change car photo</label>
                        <input type="file" name="image" class="form-control-file" id="image">
                    </div>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
              </form>
        </div>
    </div>
    </div>
</div>

resources/views/partials/car-import-modal.blade.php
<div class="modal fade" id="importModal" tabindex="-1" role="dialog" aria-labelledby="importModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">

            <form action="{{ route('car.import') }}" method="POST" name="importform"
               enctype="multipart/form-data">
                @csrf
                {{-- <input type="file" name="file" class="form-control-file">
                <br> --}}
                <a class="btn btn-info" href="{{ route('car.export') }}"> 
                 Export File</a>
                {{-- <button class="btn btn-success">Import File</button> --}}
            </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </div>
    </div>
</div>

resources/views/partials/car-modal.blade.php
<div class="modal fade" id="carModal" tabindex="-1" role="dialog" aria-labelledby="carModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="carModalLabel">New Car</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
          <form action="{{route('cars.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="name">Name</label>
                    <input type="name" class="form-control" id="name" name="name" placeholder="Porsche">
                </div>
                <div class="form-group col-md-6">
                    <label for="price">Price</label>
                    <input type="number" class="form-control" id="price" name="price" placeholder="1000">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="passengers">Passengers</label>
                    <input type="number" class="form-control" id="passengers" name="nop" placeholder="5">
                </div>
                <div class="form-group col-md-6">
                    <label for="status"><strong>Status</strong> <em>[Available=1, Not-Available=0]</em></label>
                    <select id="status" name="status" class="form-control">
                        <option value="1" selected>Available</option>
                        <option value="1">Available</option>
                        <option value="0">Not Available</option>
                    </select>
                </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                  <label for="category_id">Category</label>
                  <select id="category_id" name="category_id" class="form-control">
                    @foreach ($categories as $category)
                      <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                  </select>
              </div>
              <div class="form-group col-md-6">
                  <label for="brand_id">Brand</label>
                  <select id="brand_id" name="brand_id" class="form-control">
                    @foreach ($brands as $brand)
                      <option value="{{ $brand->id }}">{{ $brand->name }}</option>
                    @endforeach
                  </select>
              </div>
            </div>
            <div class="form-group">
              <label for="description">Description</label>
              <textarea name="description" id="description" class="form-control" cols="30" rows="4"></textarea>
            </div>
            <div class="form-group">
              <label for="image">Select car photo</label>
              <input type="file" name="image" class="form-control-file" id="image">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
          </form>
        </div>
    </div>
    </div>
</div>