routes/web.php
<?php

use RealRashid\SweetAlert\Facades\Alert;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('/', function () {
    Alert::success('Success Title', 'Success Message');
    return view('welcome');
});
Route::get('/test', function () {
    return view('test');
});

Route::get('access-denied', function () {
    return view('errors.403');
});

Route::get('/about', function () {
    return view('about');
});

Route::get('/contact', 'ContactController@index')->name('contact.index');
Route::post('/contact', 'ContactController@store')->name('contact.store');

Route::resource('cars', 'CarController');
Route::post('import', 'CarController@import')->name('car.import');
Route::get('export', 'CarController@export')->name('car.export');
Route::get('/', 'CarController@getCars')->name('cars.getCars');
Route::patch('cars/{car}', 'CarController@updateLikes')->name('cars.updateLikes');
Route::resource('brands', 'BrandController');
Route::resource('categories', 'CategoryController');
Route::resource('bookings', 'BookingController')->middleware(['auth', 'verified']);

Auth::routes(['verify' => true]);

Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

Route::group(['prefix' => 'dashboard', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@index')->name('dashboard.index');
    Route::get('/cars', 'AdminController@getCars')->name('dashboard.cars');
    Route::get('/bookings', 'AdminController@getBookings')->name('dashboard.bookings');
    Route::get('/payments', 'AdminController@payments')->name('dashboard.payments');
    Route::get('/bookings/toggle-status/{id}', 'AdminController@toggle_status')->name('bookings.status');
    Route::get('/reports', 'AdminController@reports')->name('dashboard.reports');
});

// Route::group(['prefix' => 'dashboard', 'middleware' => ['role:admin']], function() {
//     Route::get('/', 'AdminController@welcome');
//     Route::get('/manage', ['middleware' => ['permission:manage-admins'], 'uses' => 'AdminController@manageAdmins']);
// });

//**************Profiles Routes ****************************
Route::prefix('/profile')->middleware('auth')->group(function(){
    Route::get('/passwordChange','ProfileController@changePassword');
    Route::post('/passwordChange/{id}','ProfileController@postChangePassword');
    Route::get('/editProfile/{id}','ProfileController@editprofile');
    Route::post('/editprofile/{id}','ProfileController@posteditprofile');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    @livewireStyles
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/@coreui/coreui@3.0.0-rc.0/dist/css/coreui.min.css">
    
    <script src="https://unpkg.com/@coreui/coreui@3.0.0-rc.0/dist/js/coreui.min.js"></script>
</head>
<body>
    <div id="app">
        @include('layouts.navbar')
  
        @yield('content')

        @include('layouts.footer')
    </div>
    @include('sweetalert::alert')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js" integrity="sha384-L2pyEeut/H3mtgCBaUNw7KWzp5n9&#43;4pDQiExs933/5QfaTh8YStYFFkOzSoXjlTb" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"></script>
    <script>
        var picker = new Pikaday({ field: document.getElementById('datepicker') });
    </script>
</body>
</html>

resources/views/layouts/footer.blade.php
<!-- Footer -->
<footer class="bg-white">
    <div class="container py-5">
      <div class="row py-4">
        <div class="col-lg-4 col-md-6 mb-4 mb-lg-0"><img src="img/logo.png" alt="" width="180" class="mb-3">
          <p class="font-italic text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
          <ul class="list-inline mt-4">
            <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="facebook"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i class="fa fa-pinterest"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="vimeo"><i class="fa fa-vimeo"></i></a></li>
          </ul>
        </div>
        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold text-warning mb-4">Car</h6>
          <ul class="list-unstyled mb-0">
              <li class="mb-2"><a href="{{url('cars')}}" class="text-muted">Cars</a></li>
              <li class="mb-2"><a href="#" class="text-muted">Most Rented</a></li>
              <li class="mb-2"><a href="#" class="text-muted">Our Blog</a></li>
            </ul>
        </div>
        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
            <h6 class="text-uppercase font-weight-bold mb-4 text-warning">Company</h6>
            <ul class="list-unstyled mb-0">
              @guest
                <li class="mb-2"><a href="{{route('login')}}" class="text-muted">Login</a></li>
                <li class="mb-2"><a href="{{route('register')}}" class="text-muted">Register</a></li>
                @else  
                <li class="mb-2"><a href="{{route('bookings.index')}}" class="text-muted">My Bookings</a></li>
                <li class="mb-2"><a href="#" class="text-muted">Favourite Car</a></li>
              @endguest
          </ul>
        </div>
        <div class="col-lg-4 col-md-6 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Newsletter</h6>
          <p class="text-muted mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. At itaque temporibus.</p>
          <div class="p-1 rounded border">
            <div class="input-group">
              <input type="email" placeholder="Enter your email address" aria-describedby="button-addon1" class="form-control border-0 shadow-0">
              <div class="input-group-append">
                <button id="button-addon1" type="submit" class="btn btn-link"><i class="fa fa-paper-plane"></i></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Copyrights -->
    <div class="bg-light py-4">
      <div class="container text-center">
        <p class="text-muted mb-0 py-2">© 2020 Carental All rights reserved.</p>
      </div>
    </div>
  </footer>
  <!-- End -->

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-dark shadow-sm p-1 sticky-top" style="background-color: #55165F;">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
        <img src="{{asset ('images/client-logo1.png')}}" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{url('/')}}"><i class="fa fa-home"></i> HOME</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{{url('/about')}}"><i class="fa fa-globe"></i> ABOUT US</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{{ route('cars.index') }}"><i class="fa fa-car"></i> CARS</a>
                </li>
                @auth()
                <li class="nav-item">
                <a class="nav-link uppercase" href="{{ url('/dashboard') }}"><i class="fa fa-th-large"></i> DASHBOARD</a>
                </li>
                <li class="nav-item">
                <a class="nav-link uppercase" href="{{ url('/bookings') }}"><i class="fa fa-book"></i> My Bookings</a>
                </li>
                @endauth
                <li class="nav-item">
                    <a class="nav-link uppercase" href="{{ route('contact.index') }}"><i class="fa fa-phone"></i> CONTACT US</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}"><i class="fa fa-sign-in"></i> {{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}"><i class="fa fa-user-plus"></i> {{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            <img src="{{asset('images/users/'.Auth::user()->avatar)}}" alt="" class="img-responsive img-circle" style="width: 2rem; height: 2rem">
{{--                            {{ Auth::user()->name }} <span class="caret"></span>--}}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ url('/profile/editProfile/'.Auth::user()->id )}}"><i class="fa fa-user"></i> Edit Profile</a>
                            <a class="dropdown-item" href="{{ url('/profile/passwordChange') }}"><i class="fa fa-lock"></i> Manage Password</a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();"><i class="fa fa-sign-out"></i> {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>